### PR TITLE
add PageA

### PR DESCRIPTION
**Pull request by farzanashampa7**

### CODE REVIEW

**Comment by mollybeach** [comment]
you should change your branch name to PageA I don't think having spaces in branch names is good practice plus it would be good to be consistent with all of our branch names

**Review by mollybeach — COMMENTED** [review]
nice work

**Comment by farzanashampa7** [comment]
I did change my component name to PageA. I don't know what happened now!

**Review by kathleengladstone — COMMENTED** [review]
Look good

**Pull request merged**
